version: '3'

services:
  mlflow:
    build:
      context: mlflow
      dockerfile: DockerFile
    volumes:
      - ./mlflow:/app
    ports:
      - "8081:8081"
    environment:
      - MLFLOW_TRACKING_URI=http://127.0.0.1:8081
    restart: unless-stopped

  airflow:
    build:
      context: airflow
      dockerfile: DockerFile
    volumes:
      - ./data:/opt/data:rw
      - ./models:/opt/models:rw
    ports:
      - "8082:8080"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:8081
      - PROJECT_ROOT=/opt
    restart: unless-stopped

  app:
    build:
      context: app
      dockerfile: DockerFile
    ports:
      - "8080:8080"
    volumes:
      - ./app/src:/app/src
      - ./models:/app/models
    environment:
      - PROJECT_ROOT=/app
